// T039 — Banner + per-block source-map comment emitter.
//
// FR-013: every generated file carries a DO-NOT-EDIT banner referencing
// the originating spec + `composer explain` command.
// FR-014: per-block source-map comments above each rendered block.

export interface BlockMarker {
  /** Spec line that originated this block. 1-based. */
  specLine: number;
  /** Primitive discriminator literal (e.g., "Hero"). */
  primitive: string;
  /** Stable identifier of the node (typically node.id). */
  nodeId: string;
}

/**
 * Comment syntax per output language.
 * Returns either a line-comment prefix (e.g., "//") or a block-comment pair.
 */
type CommentSyntax =
  | { kind: "line"; prefix: string }
  | { kind: "block"; open: string; close: string; linePrefix: string };

function commentSyntaxFor(ext: string): CommentSyntax {
  const e = ext.toLowerCase().replace(/^\./, "");
  // Line-comment languages
  switch (e) {
    case "ts":
    case "tsx":
    case "js":
    case "jsx":
    case "mjs":
    case "cjs":
    case "rs":
    case "go":
    case "java":
    case "kt":
    case "swift":
    case "c":
    case "cpp":
    case "h":
    case "hpp":
    case "cs":
    case "scala":
    case "groovy":
    case "dart":
      return { kind: "line", prefix: "//" };
    case "py":
    case "rb":
    case "sh":
    case "bash":
    case "zsh":
    case "yaml":
    case "yml":
    case "toml":
    case "ini":
    case "conf":
    case "r":
      return { kind: "line", prefix: "#" };
    case "sql":
    case "lua":
    case "hs":
      return { kind: "line", prefix: "--" };
    case "ml":
    case "ocaml":
      return { kind: "block", open: "(*", close: "*)", linePrefix: " * " };
    case "html":
    case "xml":
    case "vue":
    case "svelte":
    case "md":
      return { kind: "block", open: "<!--", close: "-->", linePrefix: "  " };
    case "css":
    case "scss":
    case "less":
    case "sass":
      return { kind: "block", open: "/*", close: " */", linePrefix: " * " };
    default:
      return { kind: "line", prefix: "//" };
  }
}

function renderCommentBlock(syntax: CommentSyntax, lines: string[]): string {
  if (syntax.kind === "line") {
    return lines.map((l) => (l ? `${syntax.prefix} ${l}` : syntax.prefix)).join("\n");
  }
  return (
    syntax.open +
    "\n" +
    lines.map((l) => syntax.linePrefix + l).join("\n") +
    "\n" +
    syntax.close
  );
}

/**
 * Build the DO-NOT-EDIT banner that prefixes every generated file.
 * Includes a trailing blank line.
 */
export function buildBanner(specPath: string, outputPath: string, ext: string): string {
  const syntax = commentSyntaxFor(ext);
  return (
    renderCommentBlock(syntax, [
      "=====================================================================",
      "DO NOT EDIT. Generated by Composer.",
      `  spec:    ${specPath}`,
      `  inspect: composer explain ${outputPath}:LINE`,
      "=====================================================================",
    ]) + "\n\n"
  );
}

/** Build a per-block source-map comment (`from: <spec>:<line> (<primitive>, id=<nodeId>)`). */
export function buildBlockComment(specPath: string, ext: string, m: BlockMarker): string {
  const syntax = commentSyntaxFor(ext);
  return renderCommentBlock(syntax, [
    `from: ${specPath}:${m.specLine} (${m.primitive}, id=${m.nodeId})`,
  ]);
}
