// T031 — MCP `composer.compose` contract test (atomic write).

import { afterEach, beforeEach, describe, expect, it } from "vitest";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  makeFixture,
  STUB_CATALOG_INDEX,
  STUB_HERO_TEMPLATE,
  STUB_OUTPUT_MAP,
  type Fixture,
} from "../helpers/fixture.js";

describe("MCP composer.compose — atomic write (FR-003)", () => {
  let fixture: Fixture;

  beforeEach(() => {
    fixture = makeFixture({
      files: {
        "catalog/index.ts": STUB_CATALOG_INDEX,
        "templates/hero.ts.hbs": STUB_HERO_TEMPLATE,
        "output.map.ts": STUB_OUTPUT_MAP,
      },
    });
  });

  afterEach(() => fixture.cleanup());

  it("on success returns { spec_saved, files_written, audit, log, suggested_next }", async () => {
    const { compose } = (await import("@composer/core")) as {
      compose?: (
        projectRoot: string,
        specId: string,
        json: unknown,
      ) => Promise<Record<string, unknown>>;
    };
    if (!compose) throw new Error("compose() pending T043");

    const result = await compose(fixture.projectRoot, "demo", {
      primitive: "Hero",
      id: "demo",
      title: "Hello",
    });

    expect(result).toHaveProperty("spec_saved");
    expect(result).toHaveProperty("files_written");
    expect(result).toHaveProperty("audit");
    expect(result).toHaveProperty("log");
    expect(result.suggested_next).toBe("done");
  });

  it("persists the spec to design/specs/<id>.json", async () => {
    const { compose } = (await import("@composer/core")) as {
      compose?: (projectRoot: string, specId: string, json: unknown) => Promise<unknown>;
    };
    if (!compose) throw new Error("compose() pending T043");

    const specPath = join(fixture.workspaceRoot, "specs", "demo.json");
    expect(existsSync(specPath)).toBe(false);

    await compose(fixture.projectRoot, "demo", {
      primitive: "Hero",
      id: "demo",
      title: "Hello",
    });

    expect(existsSync(specPath)).toBe(true);
    const saved = JSON.parse(readFileSync(specPath, "utf8"));
    expect(saved).toEqual({ primitive: "Hero", id: "demo", title: "Hello" });
  });

  it("emits files at adapter-declared paths with the DO-NOT-EDIT banner (FR-013)", async () => {
    const { compose } = (await import("@composer/core")) as {
      compose?: (projectRoot: string, specId: string, json: unknown) => Promise<unknown>;
    };
    if (!compose) throw new Error("compose() pending T043");

    await compose(fixture.projectRoot, "demo", {
      primitive: "Hero",
      id: "demo",
      title: "Hello",
    });

    const outputPath = join(fixture.projectRoot, "src", "heroes", "demo.ts");
    expect(existsSync(outputPath)).toBe(true);
    const content = readFileSync(outputPath, "utf8");
    expect(content).toMatch(/DO NOT EDIT/);
    expect(content).toMatch(/Generated by Composer/);
    expect(content).toMatch(/composer explain/);
  });

  it("releases the lock on success (no stale lockfile)", async () => {
    const { compose } = (await import("@composer/core")) as {
      compose?: (projectRoot: string, specId: string, json: unknown) => Promise<unknown>;
    };
    if (!compose) throw new Error("compose() pending T043");

    await compose(fixture.projectRoot, "demo", {
      primitive: "Hero",
      id: "demo",
      title: "Hello",
    });

    const lockPath = join(fixture.workspaceRoot, ".composer", "cache", "compose.lock");
    expect(existsSync(lockPath)).toBe(false);
  });

  it("aborts with LOCK_HELD when another live process holds the lock (FR-CONC-002)", async () => {
    const { compose } = (await import("@composer/core")) as {
      compose?: (projectRoot: string, specId: string, json: unknown) => Promise<unknown>;
    };
    if (!compose) throw new Error("compose() pending T043");

    // Simulate a held lock by writing one referencing the current PID.
    // Lock lives inside the workspace folder (`<workspace>/.composer/cache/`),
    // not the project root (per FR-CONC-001 + data-model §11).
    const lockDir = join(fixture.workspaceRoot, ".composer", "cache");
    const lockPath = join(lockDir, "compose.lock");
    const { mkdirSync } = await import("node:fs");
    mkdirSync(lockDir, { recursive: true });
    writeFileSync(
      lockPath,
      JSON.stringify({
        pid: process.pid,
        started_at: new Date().toISOString(),
        surface: "cli",
        spec_id: "other",
      }),
    );

    await expect(
      compose(fixture.projectRoot, "demo", {
        primitive: "Hero",
        id: "demo",
        title: "Hello",
      }),
    ).rejects.toThrow(/LOCK_HELD|compose in progress/i);
  });

  it("aborts on drift (FR-015) — generated file edited by hand", async () => {
    const { compose } = (await import("@composer/core")) as {
      compose?: (projectRoot: string, specId: string, json: unknown) => Promise<unknown>;
    };
    if (!compose) throw new Error("compose() pending T043");

    // First compose lands a file.
    await compose(fixture.projectRoot, "demo", {
      primitive: "Hero",
      id: "demo",
      title: "Hello",
    });
    const outputPath = join(fixture.projectRoot, "src", "heroes", "demo.ts");

    // Hand-edit the generated file.
    writeFileSync(outputPath, "// hand-edited content that's not what compose would emit", "utf8");

    // Second compose with the same spec must abort.
    await expect(
      compose(fixture.projectRoot, "demo", {
        primitive: "Hero",
        id: "demo",
        title: "Hello",
      }),
    ).rejects.toThrow(/DRIFT_DETECTED|drift|hand-edited/i);
  });

  it("on timeout returns COMPOSE_TIMEOUT and releases the lock — retry is not LOCK_HELD (FR-008/M2)", async () => {
    const { compose, ComposeTimeoutError } = await import("@composer/core");
    // Catalog that hangs module evaluation past the budget (unref'd timer).
    const hangingCatalog =
      `import { z } from "zod";\n` +
      `await new Promise((r) => { const t = setTimeout(r, 60000); if (t && typeof t.unref === "function") t.unref(); });\n` +
      `export const Hero = z.object({ primitive: z.literal("Hero"), id: z.string(), title: z.string().min(1) }).strict();\n` +
      `export const HeroMeta = { primitive: "Hero", version: "1.0.0", intent: "x", whenToUse: "x", whenNotToUse: [], fieldGuidance: {}, examples: [{ primitive: "Hero", id: "d", title: "x" }] };\n` +
      `export const PrimitiveNode = z.discriminatedUnion("primitive", [Hero]);\n`;
    const local = makeFixture({
      composerJson: {
        workspace: "./design",
        engine: "@composer/typescript@1",
        limits: { maxComposeDurationMs: 300, maxHoldMs: 600 },
      },
      files: {
        "catalog/index.ts": hangingCatalog,
        "templates/hero.ts.hbs": STUB_HERO_TEMPLATE,
        "output.map.ts": STUB_OUTPUT_MAP,
      },
    });
    try {
      await expect(
        compose(local.projectRoot, "a", { primitive: "Hero", id: "a", title: "x" }),
      ).rejects.toBeInstanceOf(ComposeTimeoutError);

      // Lock released by the timed-out call (FR-008) — no leak.
      const lockPath = join(local.workspaceRoot, ".composer", "cache", "compose.lock");
      expect(existsSync(lockPath)).toBe(false);

      // Immediate retry must NOT see LOCK_HELD: it times out again (would be LOCK_HELD if leaked).
      let retryErr: unknown;
      try {
        await compose(local.projectRoot, "b", { primitive: "Hero", id: "b", title: "x" });
      } catch (e) {
        retryErr = e;
      }
      expect(retryErr).toBeInstanceOf(ComposeTimeoutError);
    } finally {
      local.cleanup();
    }
  });
});
